# Generated by Django 4.2.4 on 2023-08-19 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0002_source_delete_savingsgoal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
    ]
