# Generated by Django 4.2.4 on 2023-08-19 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0005_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='income',
            name='source',
        ),
        migrations.AddField(
            model_name='income',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='family.category'),
            preserve_default=False,
        ),
    ]
