# Generated by Django 4.2.4 on 2023-08-19 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0007_report'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='ending_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='report',
            name='starting_balance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
