# Generated by Django 4.2.4 on 2023-08-19 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0008_alter_report_ending_balance_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='ending_balance',
        ),
        migrations.RemoveField(
            model_name='report',
            name='starting_balance',
        ),
    ]
