# Generated by Django 4.2.4 on 2023-08-22 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0009_remove_report_ending_balance_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Transaction',
        ),
    ]
