# Generated by Django 4.2.4 on 2023-08-23 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0010_delete_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='username',
        ),
    ]
