# Generated by Django 4.2.4 on 2023-08-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0011_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(default=2, max_length=30, unique=True),
            preserve_default=False,
        ),
    ]
