# Generated by Django 4.2.4 on 2023-08-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0012_userprofile_first_name_userprofile_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
