# Generated by Django 4.2.4 on 2023-08-24 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('family', '0013_userprofile_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
